import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:crypto/crypto.dart';
import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_web_auth_2/flutter_web_auth_2.dart';
import 'package:sign_in_with_apple/sign_in_with_apple.dart';

import '../core/storage/secure_store.dart';
import '../core/helpers/password_changer.dart';

class AuthService {
  AuthService(this._secureStore);

  static const _tokenKey = 'auth_access_token';
  final SecureStore _secureStore;

  Future<bool> login(String email, String password) async {
    if (email.isEmpty || password.isEmpty) return false;
    
    try {
      final encryptedPassword = PasswordChanger.encryptNewPassword(password);
      final dio = Dio();
      final response = await dio.post(
        'https://principles-server.ckwavh.easypanel.host/api/account/login',
        data: {
          'Email': email,
          'Password': encryptedPassword,
        },
      );

      final appToken = response.data['token'] ?? response.data['Token'];
      if (appToken != null) {
        await _secureStore.write(_tokenKey, appToken);
        return true;
      }
      return false;
    } catch (e) {
      debugPrint('Login Error: $e');
      return false;
    }
  }

  Future<bool> register({
    required String name,
    required String email,
    required String password,
    required int gender,
    String? mission,
    String? slogan,
  }) async {
    if (email.isEmpty || password.isEmpty || name.isEmpty) return false;

    try {
      final encryptedPassword = PasswordChanger.encryptNewPassword(password);
      final dio = Dio();
      final response = await dio.post(
        'https://principles-server.ckwavh.easypanel.host/api/account/signup',
        data: {
          'Name': name,
          'Email': email,
          'Password': encryptedPassword,
          'Gender': gender,
          if (mission != null && mission.isNotEmpty) 'Mission': mission,
          if (slogan != null && slogan.isNotEmpty) 'MainSlogan': slogan,
        },
      );

      final appToken = response.data['token'] ?? response.data['Token'];
      if (appToken != null) {
        await _secureStore.write(_tokenKey, appToken);
        return true;
      }
      
      // If backend doesn't return token on signup, call login automatically
      return await login(email, password);
    } catch (e) {
      debugPrint('Registration Error: $e');
      return false;
    }
  }

  Future<void> logout() => _secureStore.delete(_tokenKey);

  Future<String?> getToken() => _secureStore.read(_tokenKey);

  Future<bool> googleAuthorize() async {
    try {
      final String clientId = !kIsWeb && Platform.isIOS
          ? '40949920786-ufvoeeof4s82011n4got9udapd6pm35e.apps.googleusercontent.com'
          : '40949920786-030cht7nm5a2q2hi4jgm7leldfcc6miu.apps.googleusercontent.com';

      // 1. Generate PKCE verifier and challenge
      final random = Random.secure();
      final verifierBytes = List<int>.generate(32, (_) => random.nextInt(256));
      final codeVerifier = base64UrlEncode(verifierBytes).replaceAll('=', '');

      final challengeBytes = sha256.convert(ascii.encode(codeVerifier)).bytes;
      final codeChallenge = base64UrlEncode(challengeBytes).replaceAll('=', '');

      const callbackScheme = 'com.set.principles';
      const redirectUri = '$callbackScheme:/oauth2redirect';

      // 2. Build URL
      final authUrl = Uri.https('accounts.google.com', '/o/oauth2/v2/auth', {
        'client_id': clientId,
        'redirect_uri': redirectUri,
        'response_type': 'code',
        'scope': 'openid profile email https://www.googleapis.com/auth/user.gender.read',
        'code_challenge': codeChallenge,
        'code_challenge_method': 'S256',
        'access_type': 'offline',
      });

      // 3. Open Browser
      final result = await FlutterWebAuth2.authenticate(
        url: authUrl.toString(),
        callbackUrlScheme: callbackScheme,
      );

      // 4. Get code from the redirect
      final resultUri = Uri.parse(result);
      final code = resultUri.queryParameters['code'];
      final error = resultUri.queryParameters['error'];

      if (error != null || code == null) {
        throw Exception('Code generated by Google to get tokens is null or error occurred: $error');
      }

      // 5. Exchange code for tokens
      final dio = Dio();
      final tokenResponse = await dio.post(
        'https://oauth2.googleapis.com/token',
        data: {
          'code': code,
          'client_id': clientId,
          'redirect_uri': redirectUri,
          'grant_type': 'authorization_code',
          'code_verifier': codeVerifier,
        },
        options: Options(contentType: Headers.formUrlEncodedContentType),
      );

      final accessToken = tokenResponse.data['access_token'];
      final idToken = tokenResponse.data['id_token'];

      if (accessToken == null || idToken == null) return false;

      // 6. Send to backend
      const backendUrl = 'https://principles-server.ckwavh.easypanel.host/api/account/googleauthorization';
      final backendResponse = await dio.post(
        backendUrl,
        data: {
          'AccessToken': accessToken,
          'IdToken': idToken,
        },
      );

      final appToken = backendResponse.data['token'] ?? backendResponse.data['Token']; // ASP.NET might return camelCase or PascalCase
      if (appToken == null) return false;

      // 7. Save token
      await _secureStore.write(_tokenKey, appToken);

      return true;
    } catch (e) {
      debugPrint('Google Auth Error: $e');
      return false;
    }
  }

  Future<bool> appleAuthorize() async {
    try {
      final isAvailable = await SignInWithApple.isAvailable();
      if (!isAvailable) {
        throw Exception('AppleAuthUnavailableOnDevice');
      }

      final credential = await SignInWithApple.getAppleIDCredential(
        scopes: [
          AppleIDAuthorizationScopes.email,
          AppleIDAuthorizationScopes.fullName,
        ],
      );

      final idToken = credential.identityToken;
      if (idToken == null || idToken.isEmpty) {
        throw Exception('Apple ID token is null or empty.');
      }

      // Відправляємо IdToken на власний бекенд
      const backendUrl = 'https://principles-server.ckwavh.easypanel.host/api/account/appleauthorization';
      final dio = Dio();
      final backendResponse = await dio.post(
        backendUrl,
        data: {
          'IdToken': idToken,
        },
      );

      final appToken = backendResponse.data['token'] ?? backendResponse.data['Token'];
      if (appToken == null) return false;

      await _secureStore.write(_tokenKey, appToken);
      return true;
    } on SignInWithAppleAuthorizationException catch (e) {
      if (e.code == AuthorizationErrorCode.canceled) {
        debugPrint('Apple Auth canceled by user (code 1001 equivalent).');
      } else {
        debugPrint('Apple Auth Exception: $e');
      }
      return false;
    } catch (e) {
      debugPrint('Apple Auth Error: $e');
      return false;
    }
  }
}
