import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:crypto/crypto.dart';
import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_web_auth_2/flutter_web_auth_2.dart';

import '../core/storage/secure_store.dart';

class AuthService {
  AuthService(this._secureStore);

  static const _tokenKey = 'auth_access_token';
  final SecureStore _secureStore;

  Future<bool> login(String email, String password) async {
    if (email.isEmpty || password.isEmpty) return false;
    await _secureStore.write(_tokenKey, 'fake_token');
    return true;
  }

  Future<bool> register(String email, String password) async {
    if (email.isEmpty || password.isEmpty) return false;
    await _secureStore.write(_tokenKey, 'fake_token');
    return true;
  }

  Future<void> logout() => _secureStore.delete(_tokenKey);

  Future<String?> getToken() => _secureStore.read(_tokenKey);

  Future<bool> googleAuthorize() async {
    try {
      final String clientId = !kIsWeb && Platform.isIOS
          ? '40949920786-ufvoeeof4s82011n4got9udapd6pm35e.apps.googleusercontent.com'
          : '40949920786-030cht7nm5a2q2hi4jgm7leldfcc6miu.apps.googleusercontent.com';

      // 1. Generate PKCE verifier and challenge
      final random = Random.secure();
      final verifierBytes = List<int>.generate(32, (_) => random.nextInt(256));
      final codeVerifier = base64UrlEncode(verifierBytes).replaceAll('=', '');

      final challengeBytes = sha256.convert(ascii.encode(codeVerifier)).bytes;
      final codeChallenge = base64UrlEncode(challengeBytes).replaceAll('=', '');

      const callbackScheme = 'com.set.principles';
      const redirectUri = '$callbackScheme:/oauth2redirect';

      // 2. Build URL
      final authUrl = Uri.https('accounts.google.com', '/o/oauth2/v2/auth', {
        'client_id': clientId,
        'redirect_uri': redirectUri,
        'response_type': 'code',
        'scope': 'openid profile email https://www.googleapis.com/auth/user.gender.read',
        'code_challenge': codeChallenge,
        'code_challenge_method': 'S256',
        'access_type': 'offline',
      });

      // 3. Open Browser
      final result = await FlutterWebAuth2.authenticate(
        url: authUrl.toString(),
        callbackUrlScheme: callbackScheme,
      );

      // 4. Get code from the redirect
      final resultUri = Uri.parse(result);
      final code = resultUri.queryParameters['code'];
      final error = resultUri.queryParameters['error'];

      if (error != null || code == null) {
        throw Exception('Code generated by Google to get tokens is null or error occurred: $error');
      }

      // 5. Exchange code for tokens
      final dio = Dio();
      final tokenResponse = await dio.post(
        'https://oauth2.googleapis.com/token',
        data: {
          'code': code,
          'client_id': clientId,
          'redirect_uri': redirectUri,
          'grant_type': 'authorization_code',
          'code_verifier': codeVerifier,
        },
        options: Options(contentType: Headers.formUrlEncodedContentType),
      );

      final accessToken = tokenResponse.data['access_token'];
      final idToken = tokenResponse.data['id_token'];

      if (accessToken == null || idToken == null) return false;

      // 6. Send to backend
      const backendUrl = 'https://principles-server.ckwavh.easypanel.host/api/account/googleauthorization';
      final backendResponse = await dio.post(
        backendUrl,
        data: {
          'AccessToken': accessToken,
          'IdToken': idToken,
        },
      );

      final appToken = backendResponse.data['token'] ?? backendResponse.data['Token']; // ASP.NET might return camelCase or PascalCase
      if (appToken == null) return false;

      // 7. Save token
      await _secureStore.write(_tokenKey, appToken);

      return true;
    } catch (e) {
      debugPrint('Google Auth Error: $e');
      return false;
    }
  }

  Future<bool> appleAuthorize() async {
    // Placeholder for Apple OAuth
    await Future.delayed(const Duration(seconds: 1));
    await _secureStore.write(_tokenKey, 'fake_apple_token');
    return true;
  }
}
