platform :osx, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'ephemeral', 'Flutter-Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Flutter-Generated.xcconfig, then run \"flutter pub get\""
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_macos_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_macos_build_settings(target)
    target.build_configurations.each do |config|
      deployment = config.build_settings['MACOSX_DEPLOYMENT_TARGET']
      if deployment.nil? || deployment.to_f < 11.0
        config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
    # PrivacyInfo.xcprivacy must not be compiled as a source file.
    target.build_phases.each do |phase|
      next unless phase.respond_to?(:files)
      phase.files.to_a.each do |build_file|
        path = build_file.file_ref&.path
        next unless path&.end_with?('PrivacyInfo.xcprivacy')
        phase.remove_build_file(build_file) if phase.is_a?(Xcodeproj::Project::Object::PBXSourcesBuildPhase)
      end
    end
  end
end
